FIXED: docker build commented out, triggering of release flow from tag creation in CI flow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,8 +3,28 @@ on:
   push:
     tags:
       - 'v*.*.*'
+  repository_dispatch:
+    types: [trigger-release]
 
 jobs:
+  prepare-release:
+    name: Prepare release flow
+    runs-on: ubuntu-latest
+    outputs:
+      release_tag: ${{ steps.get_release_tag.outputs.release_tag }}
+    steps:
+      - name: Get release tag
+        id: get_release_tag
+        run: |
+          if [[ "${{ github.event_name }}" == "push" ]]; then
+            echo "release_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
+          elif [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
+            echo "release_tag=v${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT
+          else
+            echo "ERROR: Unsupported event type: ${{ github.event_name }}"
+            exit 1
+          fi
+
   release-pypi:
     name: Release package to PyPI
     runs-on: ubuntu-latest
@@ -13,13 +33,20 @@ jobs:
       url: https://pypi.org/project/strato-dns-api/
     permissions:
       id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
+    needs: prepare-release
     steps:
       - uses: actions/checkout@v4
-
-      - name: Download artifact from main branch build
-        uses: actions/download-artifact@v4
         with:
-          name: dist
+          ref: ${{ needs.prepare-release.outputs.release_tag }}
+
+      - name: Download python package from CI workflow
+        uses: dawidd6/action-download-artifact@v3
+        with:
+          workflow: ci.yml                # Name or ID of the workflow
+          workflow_conclusion: success    # Only from successful runs
+          branch: main                    # From main branch
+          name: dist                      # Artifact name
+          path: ./dist                    # Where to download
 
       - name: publish
         # gh-action-pypi-publish uses TWINE_PASSWORD automatically
@@ -31,31 +58,42 @@ jobs:
     environment:
       name: DockerHub
       url: https://hub.docker.com/repository/docker/slinred/strato-acme/general
+    needs: prepare-release
     steps:
     - uses: actions/checkout@v4
+      with:
+          ref: ${{ needs.prepare-release.outputs.release_tag }}
 
     - name: docker buildx setup
       uses: docker/setup-buildx-action@v3.10.0
 
-    - name: login to DockerHub
+    - name: Tag and push docker image
       env: 
-        DOCKERHUB_LOGIN: ${{ vars.DOCKERHUB_LOGIN }}
-        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
+          DOCKERHUB_LOGIN: ${{ vars.DOCKERHUB_LOGIN }}
+          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
       run: |
+        COMMIT_SHORT=${GITHUB_SHA:0:8}
+        VERSION=$(cat VERSION)
+
         echo $DOCKERHUB_TOKEN | docker login -u "$DOCKERHUB_LOGIN" --password-stdin
 
-    - name: Build and push the docker image
-      run: RELEASE_BUILD=true /bin/bash ./docker/build.sh --push
+        # Get the image built in the CI workflow
+        docker pull slinred/strato-acme:${COMMIT_SHORT}
+        # Tag the image with the version tag
+        docker tag slinred/strato-acme:${COMMIT_SHORT} slinred/strato-acme:${VERSION}
+        # Push the version tagged image to DockerHub
+        docker push slinred/strato-acme:${VERSION}
 
-    - name: Clean up
-      run: |
-        docker logout
+        docker logout || true
 
   release-github:
     name: Create GitHub Release
     runs-on: ubuntu-latest
+    needs: [ prepare-release, release-pypi, release-docker ]
     steps:
       - uses: actions/checkout@v4
+        with:
+          ref: ${{ needs.prepare-release.outputs.release_tag }}
 
       - name: Set up Python
         uses: actions/setup-python@v4
@@ -65,7 +103,7 @@ jobs:
       - name: Get changelog
         id: changelog
         run: |
-          VERSION=${GITHUB_REF#refs/tags/v}
+          VERSION=$(cat VERSION)
           python3 ./scripts/version_changelog.py ${VERSION} > version_changelog.md
       
       - name: Create GitHub Release
